"""Workspace isolation, CAS history and immutable research run snapshots."""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("settings_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "action_receipts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("action_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "actor_id", "action_key", name="uq_action_key"),
    )
    op.create_table(
        "research_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy", sa.String(length=40), nullable=False),
        sa.Column("coverage_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    with op.batch_alter_table("research_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_runs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "studio_documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("studio_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_studio_documents_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_studio_documents_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_studio_documents_state"), ["state"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_studio_documents_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "workspace_members",
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("publish_permission", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "research_findings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column("topic_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disposition", sa.String(length=40), nullable=False),
        sa.Column("duplicate_group_id", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("dimensions_json", sa.Text(), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "canonical_url", name="uq_run_finding_url"),
    )
    with op.batch_alter_table("research_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_findings_disposition"), ["disposition"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_research_findings_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_research_findings_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "studio_versions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["studio_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "revision", name="uq_studio_version"),
    )
    with op.batch_alter_table("studio_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_studio_versions_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_studio_versions_workspace_id"), ["workspace_id"], unique=False
        )

    job_columns = {column["name"] for column in sa.inspect(op.get_bind()).get_columns("jobs")}
    if "cancel_requested" not in job_columns:
        op.add_column(
            "jobs",
            sa.Column("cancel_requested", sa.Boolean(), nullable=False, server_default=sa.false()),
        )
    if "heartbeat_at" not in job_columns:
        op.add_column("jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True))
    legacy = "00000000-0000-4000-8000-000000000001"
    for table in [
        "posts",
        "topics",
        "jobs",
        "article_evidence",
        "source_candidates",
        "slides",
        "publish_attempts",
        "audit",
        "daily_runs",
        "media_assets",
        "topic_approvals",
        "post_revisions",
        "publish_schedules",
        "usage_events",
    ]:
        columns = {column["name"] for column in sa.inspect(op.get_bind()).get_columns(table)}
        if "workspace_id" not in columns:
            op.add_column(
                table, sa.Column("workspace_id", sa.String(), nullable=False, server_default=legacy)
            )
            op.create_index(f"ix_{table}_workspace_id", table, ["workspace_id"])
        if table in ["topics", "article_evidence", "source_candidates"]:
            field = "source_url" if table == "article_evidence" else "url"
            constraints = sa.inspect(op.get_bind()).get_unique_constraints(table)
            naming = {"uq": "uq_%(table_name)s_%(column_0_name)s"}
            with op.batch_alter_table(table, naming_convention=naming) as batch:
                for constraint in constraints:
                    if constraint["column_names"] == [field]:
                        batch.drop_constraint(
                            constraint["name"] or f"uq_{table}_{field}", type_="unique"
                        )
                if not any(c["column_names"] == ["workspace_id", field] for c in constraints):
                    batch.create_unique_constraint(
                        f"uq_{table}_workspace_url", ["workspace_id", field]
                    )
    op.execute(
        sa.text(
            "INSERT INTO workspaces (id,name,revision,settings_json,created_at) VALUES (:id,'Personal studio',1,'{}',CURRENT_TIMESTAMP)"
        ).bindparams(id=legacy)
    )
    op.execute(
        sa.text(
            "INSERT INTO workspace_members (workspace_id,user_id,role,publish_permission) SELECT :id,id,CASE WHEN role='admin' THEN 'owner' ELSE role END,CASE WHEN role IN ('admin','reviewer') THEN 1 ELSE 0 END FROM users"
        ).bindparams(id=legacy)
    )


def downgrade():
    # Refuse removal when multiple studios would collapse URL identity or leak data.
    count = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM workspaces")).scalar()
    if count > 1:
        raise RuntimeError("Export and consolidate studios before downgrading workspace isolation")
    with op.batch_alter_table("jobs") as batch:
        batch.drop_column("cancel_requested")
        batch.drop_column("heartbeat_at")
    for table in [
        "research_findings",
        "studio_versions",
        "workspace_members",
        "research_runs",
        "studio_documents",
        "action_receipts",
    ]:
        op.drop_table(table)
    for table in [
        "posts",
        "topics",
        "jobs",
        "article_evidence",
        "source_candidates",
        "slides",
        "publish_attempts",
        "audit",
        "daily_runs",
        "media_assets",
        "topic_approvals",
        "post_revisions",
        "publish_schedules",
        "usage_events",
    ]:
        with op.batch_alter_table(table) as batch:
            if table in ["topics", "article_evidence", "source_candidates"]:
                field = "source_url" if table == "article_evidence" else "url"
                batch.drop_constraint(f"uq_{table}_workspace_url", type_="unique")
                batch.create_unique_constraint(f"uq_{table}_{field}", [field])
            batch.drop_index(f"ix_{table}_workspace_id")
            batch.drop_column("workspace_id")
    op.drop_table("workspaces")
